// Core
export type {
  Articulation,
  DynamicMarking,
  Pitch,
  NoteEvent,
  TimeSignature,
  TempoMark,
  KeyCenter,
  Part,
  TuningSystem,
  ScoreSettings,
  Score,
} from './core/index.js';

export {
  createScore,
  pitchFromMidi,
  addPart,
  removePart,
  addNote,
  removeNote,
  getAllEvents,
  getEventsAtTick,
  getEventsInRange,
  tickToSeconds,
  secondsToTick,
  getScoreDuration,
  cloneScore,
  mergeScores,
} from './core/index.js';

// Pitch analysis
export type { ForteEntry, Scale, Chord, SpelledPitch, SpellingKeyContext, Monzo, Rank2Temperament, Val, MosEntry, VoiceLeadingMetric, OPTICResult } from './pitch/index.js';
export {
  normalizePc,
  pitchFromPcOctave,
  pitchToFrequency,
  frequencyToPitch,
  pitchClassName,
  pitchClassFlatName,
  pitchName,
  parsePitchName,
  directedInterval,
  intervalClass,
  intervalClassName,
  semitoneDist,
  PitchClassSet,
  FORTE_CATALOG,
  FORTE_BY_NAME,
  voiceLeadingDistance,
  smoothestVoiceLeading,
  pcDistance,
  // Scales, modes, and chords
  SCALE_CATALOG,
  CHORD_CATALOG,
  scaleFromPcs,
  scaleFromIntervals,
  modeRotation,
  chordFromPcs,
  chordFromName,
  chordFromIntervals,
  // Tuning systems
  equalTemperament,
  TET_12,
  TET_19,
  TET_24,
  TET_31,
  TET_53,
  PYTHAGOREAN,
  JUST_5_LIMIT,
  JUST_7_LIMIT,
  QUARTER_COMMA_MEANTONE,
  centsDeviation,
  frequencyFromTuning,
  nearestStep,
  // PCS similarity
  icvsim,
  angleSimilarity,
  pcSetCosine,
  zRelation,
  earthMoversDistance,
  // Cent/ratio/EDO conversions
  centsBetween,
  centsToRatio,
  ratioToCents,
  edoStepToCents,
  centsToEdoStep,
  ratioToEdoStep,
  // Pitch spelling
  spellPitch,
  spellPitchSequence,
  // Monzo arithmetic
  monzoToCents,
  monzoToRatio,
  ratioToMonzo,
  monzoAdd,
  monzoSubtract,
  monzoScale,
  // Rank-2 temperaments, MOS scales, vals
  mosScale,
  mosStepPattern,
  isMos,
  mosTree,
  patentVal,
  valMapping,
  temperamentError,
  isBadlyBroken,
  MEANTONE,
  SUPERPYTH,
  FLATTONE,
  MAVILA,
  // Geometric voice leading
  voiceLeadingVector,
  geometricDistance,
  opticEquivalence,
  parsimonyScore,
  commonToneCount,
  isParsimoniousConnection,
} from './pitch/index.js';

// Time analysis
export type { MetricLevel, MetricOptions, Pattern, PatternOptions, GrooveOptions, MPRWeights, MetricalPreferenceResult, MetricalPreferenceOptions, GroupingBoundary, GroupingOptions, MetricalGridEntry } from './time/index.js';
export {
  buildMetricLevels,
  beatStrength,
  maxBeatStrength,
  syncopation,
  metricPosition,
  findPatterns,
  quantize,
  swing,
  durationName,
  durationTicks,
  // Rhythmic complexity
  lzComplexity,
  syncopationIndex,
  weightedNoteToBeatDistance,
  grooveScore,
  // GTTM preference rules
  metricalPreference,
  groupingBoundaries,
  hierarchicalMeter,
} from './time/index.js';

// Tension analysis
export type { TensionWeights, TensionOptions, TensionPoint, TensionCurve, TensionProfile, TonalIntervalVector, DFTComponents, TPSKey, TPSChord, SpiralPoint, ScoreTensionPoint, ScoreTensionOptions } from './tension/index.js';
export {
  roughness,
  roughnessFromMidi,
  computeTension,
  tensionVelocity,
  tensionAcceleration,
  tensionIntegral,
  findTensionPeaks,
  findTensionValleys,
  classifyTensionProfile,
  // Tonal Pitch Space
  basicSpace,
  tpsDistance,
  surfaceDissonance,
  melodicAttraction,
  // TIV / DFT
  chromaVector,
  tiv,
  tivDistance,
  tivConsonance,
  dftCoefficients,
  // Spiral Array
  spiralArrayPosition,
  centerOfEffect,
  cloudDiameter,
  cloudMomentum,
  tensileStrain,
  // Score-level tension curves
  scoreTension,
  tpsTensionCurve,
  spiralTensionCurve,
  tivTensionCurve,
} from './tension/index.js';

// I/O
export type { ScoreJSON, SclDegree, SclData, KbmData, XmlElement, XmlSerializeOptions, MusicXmlWarning, MusicXmlImportResult, MusicXmlExportOptions, KernImportResult, KernWarning, AbcImportResult, AbcWarning, MeiImportResult, MeiWarning, LilyPondExportOptions, JamsObservation, JamsAnnotation, JamsDocument, RomanTextChord, RomanTextMeasure, RomanTextAnalysis } from './io/index.js';
export { midiToScore, scoreToMidi, scoreToJSON, scoreFromJSON, parseScl, parseKbm, tuningFromScl, sclToString, kbmToString, parseXml, serializeXml, createElement, findChild, findChildren, textContent, childText, childInt, musicXmlToScore, scoreToMusicXML, kernToScore, abcToScore, meiToScore, scoreToLilyPond, toJAMS, toRomanText, fromRomanText } from './io/index.js';

// Rendering
export type {
  RenderOptions,
  TensionRenderOptions,
  OverlayOptions,
  ColorStop,
  PCDistributionOptions,
  ICV,
  ICVRadarOptions,
  CircleOfFifthsOptions,
  FormSection,
  FormDiagramOptions,
  SSMHeatmapOptions,
  TonnetzOptions,
  ChordGraphOptions,
  JILatticeNode,
  JILatticeOptions,
  PitchSpacePlotOptions,
  WavescapeOptions,
} from './render/index.js';
export {
  renderChromaticStaff,
  renderTensionCurve,
  renderOverlay,
  escapeXml,
  svgOpen,
  svgClose,
  svgEmpty,
  colorRamp,
  VIRIDIS_STOPS,
  hslToRgb,
  polylinePoints,
  renderPCDistribution,
  renderICVRadar,
  renderCircleOfFifths,
  renderFormDiagram,
  renderSSM,
  renderTonnetz,
  renderChordGraph,
  renderJILattice,
  renderPitchSpacePlot,
  renderWavescape,
} from './render/index.js';

// Analysis
export type {
  ChordLabel,
  HarmonicEvent,
  RomanNumeral,
  ContourDirection,
  PitchRange,
  CurvePoint,
  EnvelopePoint,
  KeyProfile,
  KeyCandidate,
  KeyDetectionResult,
  KeyDetectionOptions,
  WindowedKeyResult,
  RomanNumeralKey,
  EnhancedRomanNumeral,
  Triad,
  NRTOperation,
  SeventhChord,
  SeventhChordQuality,
  NRT7Operation,
  // Self-similarity
  SimilarityMatrix,
  NoveltyPoint,
  FeatureExtractor,
  StructuralBoundary,
  // Serial
  TwelveToneRow,
  TwelveToneMatrix,
  RowForm,
  RowFormIdentification,
  AllCombinatorialType,
  AllCombinatorialClassification,
  AllIntervalRowOptions,
  SegmentalInvarianceResult,
  SegmentMapping,
  DerivedRowResult,
  DerivedRowTransformation,
  // Stats
  MarkovChain,
  ZipfResult,
  StyleFingerprint,
  // Chord-scale
  ToneClassification,
  ScaleTone,
  ChordScaleMatch,
  NoteHarmonyClassification,
  // Modulation
  ModulationPoint,
  // Voice separation
  VoiceSeparationOptions,
  Voice,
  VoiceSeparationResult,
  // Counterpoint
  MotionType,
  MotionClassification,
  ViolationType,
  ViolationSeverity,
  CounterpointViolation,
  CounterpointOptions,
  CounterpointResult,
  // Texture
  TextureClass,
  TexturePoint,
  // Harmonic network
  ChordNode,
  ChordEdge,
  ChordGraph,
  GraphMetrics,
  CommunityResult,
  GraphComparison,
  // Evaluation
  AccuracyResult,
  KeyAccuracyResult,
  PrecisionRecallResult,
  EvalKey,
  Segment,
  OverlapResult,
  // SIA/SIATEC
  MusicPoint,
  TranslationVector,
  SIAPattern,
  TEC,
  CosiatecResult,
  // Information-theoretic expectation
  Viewpoint,
  MarkovModel,
  ICPoint,
  EntropyPoint,
  // Figured bass
  FBAccidental,
  FBInterval,
  ParsedFiguredBass,
  FiguredBassKey,
  RealizedChord,
  FiguredBassAnalysisOptions,
  FiguredBassEvent,
  // K-net / GIS
  KNetArrowType,
  KNetArrow,
  KNet,
  IsographyResult,
  GIS,
} from './analysis/index.js';
export {
  identifyChord,
  identifyScale,
  harmonicRhythm,
  romanNumeralAnalysis,
  contour,
  range,
  meanPitch,
  intervalHistogram,
  stepLeapRatio,
  segmentByRests,
  segmentByPattern,
  eventDensityCurve,
  registralEnvelope,
  // Self-similarity & novelty
  chromaticFeature,
  selfSimilarityMatrix,
  noveltyDetection,
  noveltyPeaks,
  multiScaleNovelty,
  findStructuralBoundaries,
  // Key detection
  detectKey,
  detectKeyWindowed,
  detectKeyTIV,
  keyName,
  pcDistribution,
  // Enhanced Roman numeral analysis
  enhancedRomanNumeral,
  functionalHarmonyScore,
  chordQualityFromSymbol,
  detectModulations,
  // Neo-Riemannian transforms
  nrtTransform,
  classifyNRT,
  nrtCompound,
  nrtPath,
  hexatonicCycle,
  octatonicCycle,
  hexatonicPole,
  weitzmannRegion,
  triadPitchClasses,
  seventhChordPitchClasses,
  nrt7Transform,
  classifyNRT7,
  nrt7Compound,
  nrt7Path,
  // Twelve-tone serial
  createRow,
  twelvetoneMatrix,
  getRowForm,
  rowMultiply,
  rowRotate,
  combinatoriality,
  invariantPcs,
  identifyForm,
  isAllInterval,
  allIntervalRows,
  multiply,
  M5,
  M7,
  setMultiplication,
  intervalExpansion,
  isHexachordallyCombinatorialP,
  isHexachordallyCombinatorialI,
  isHexachordallyCombinatorialR,
  isHexachordallyCombinatorialRI,
  isAllCombinatorialHexachord,
  classifyAllCombinatorialType,
  segmentalInvariance,
  derivedRow,
  // Statistical analysis
  shannonEntropy,
  rhythmicEntropy,
  zipfDistribution,
  markovTransition,
  markovGenerate,
  ngramCounts,
  pitchDistribution,
  intervalDistribution,
  durationDistribution,
  chordTypeDistribution,
  styleFingerprint,
  styleSimilarity,
  // Chord-scale theory
  chordScaleMatch,
  classifyTones,
  availableTensions,
  avoidNotes,
  hpcp,
  chordScaleScore,
  bestChordScale,
  analyzeOverHarmony,
  // Voice separation
  separateVoices,
  // Counterpoint analysis
  checkFirstSpecies,
  checkSecondSpecies,
  checkFourthSpecies,
  contrapuntalMotion,
  // Textural analysis
  textureType,
  rhythmicIndependence,
  textureProfile,
  voiceCount,
  // Harmonic network analysis
  chordTransitionGraph,
  transitionProbabilities,
  graphCentrality,
  detectCommunities,
  findCycles,
  compareGraphs,
  // Evaluation metrics
  chordAccuracy,
  keyAccuracy,
  segmentationPrecisionRecall,
  voiceSeparationAccuracy,
  overlapRatio,
  // SIA/SIATEC
  pointSetRepresentation,
  sia,
  siatec,
  cosiatec,
  compressionRatio,
  // Information-theoretic expectation
  VIEWPOINT_PITCH,
  VIEWPOINT_MIDI,
  VIEWPOINT_INTERVAL,
  VIEWPOINT_CONTOUR,
  VIEWPOINT_DURATION,
  viewpointScaleDegree,
  buildMarkovModel,
  informationContent,
  contextEntropy,
  surpriseCurve,
  entropyCurve,
  combineModels,
  // Figured bass
  parseFiguredBass,
  realizeFiguredBass,
  figuredBassAnalysis,
  // K-net / GIS
  buildKNet,
  kNetIsography,
  buildGIS,
  gisInterval,
  pitchClassGIS,
  pitchGIS,
  durationGIS,
} from './analysis/index.js';

// Composition
export type {
  WeightedOption,
  ProductionRule,
  SymbolMapping,
  LSystemEvent,
  CellGrid,
  CAMapping,
  CAEvent,
  ParallelViolation,
  CrossingViolation,
  RangeViolation,
  LeapViolation,
} from './composition/index.js';
export {
  // Stochastic generators
  poissonOnsets,
  gaussianPitches,
  uniformRhythm,
  exponentialDurations,
  cauchyPitches,
  weightedChoice,
  // Xenakis Sieve
  Sieve,
  sieve,
  // L-System
  LSystem,
  PITCH_MAPPING,
  RHYTHM_MAPPING,
  // Cellular Automaton
  elementaryCA,
  gameOfLife,
  caToEvents,
  // Composition Constraints
  checkParallelFifths,
  checkParallelOctaves,
  checkVoiceCrossing,
  isInRange,
  checkLeapResolution,
} from './composition/index.js';
